-- ====== Arquivos SQL necessários para início  da aplicação =====

CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL,
    NOME VARCHAR,
    URL VARCHAR,
    CATEGORIA VARCHAR,
    PESO VARCHAR,
    COR VARCHAR,
    DESCONTO VARCHAR,
    CLASSIFICACAO VARCHAR,
    PRECO VARCHAR
);

CREATE SEQUENCE PRODUCT_ID START WITH 1;